name: john-vps

include:
  - path: "./proxy/docker-compose.yml"
  - path: "./apps/chatpardy/docker-compose.yml"
  - path: "./apps/homepage/docker-compose.yml"
  - path: "./apps/codered/docker-compose.yml"
  - path: "./apps/plucker/docker-compose.yml"
  - path: "./apps/deckards/docker-compose.yml"

